import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ojuju, titillium_web } from "@/fonts/main.fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${ojuju.variable} ${titillium_web.variable}`}>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
